<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Analyzer" PrivateAssets="all" />
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Quill.AzureDevOps\Quill.AzureDevOps.csproj" />
    <ProjectReference Include="..\..\src\Quill.Core\Quill.Core.csproj" />
    <ProjectReference Include="..\Quill.Tests.Shared\Quill.Tests.Shared.csproj" />
  </ItemGroup>

</Project>
