<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Quill.Core\Quill.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Analyzer" PrivateAssets="all" />
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="all" />
  </ItemGroup>

</Project>
